/*
 * SPDX-License-Identifier: GPL-3.0-or-later
 * Copyright (C) 2026-present The CortenaOS Project
 */
package framework.cortena.ui.shape

/**
 * Corner rendering mode for a [framework-agnostic] shape.
 * - [Circular] uses constant-radius circular arcs at each corner. This is the standard rounded
 *   rectangle most platforms produce by default.
 * - [Continuous] uses a continuous-curvature (squircle-like) curve generated by [CornerBuilder]. It
 *   avoids the discontinuity in curvature where an arc meets a straight edge, producing the smooth
 *   "iOS / Squircle" look at the cost of slightly more expensive path construction.
 */
public enum class CornerStyle {
    Circular,
    Continuous,
}
